class SwatchGenerator {
  constructor() {
    this.ART_SWATCHES = [
      new Swatch({
        id: "default-white-on-black",
        label: "White on Black",
        colors: ["#FFFFFF"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "inverted-black-on-white",
        label: "Black on White",
        colors: ["#000000"],
        backgroundColor: "#FFFFFF",
      }),
      new Swatch({
        id: "fire-mint",
        label: "Fire Mint",
        colors: ["#FF0000", "#00FFFF"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "hell-is-other-demons",
        label: "Hell Is Other Demons",
        colors: ["#FFFFFF", "#3b00a6", "#ff0063"],
        backgroundColor: "#020b14",
      }),
      new Swatch({
        id: "fun-dip",
        label: "Fun Dip",
        colors: ["#8CEEEE", "#26BFBF", "#FF8A47", "#FC6170", "#FFD747"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "cyber-samurai",
        label: "Cyber Samurai",
        colors: ["#e9275b", "#f44d9b", "#5de8e5"],
        backgroundColor: "#392270",
      }),
      new Swatch({
        id: "electric-citrus",
        label: "Electric Citrus",
        colors: ["#0066FF", "#EB00FF", "#FFE500"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "superway",
        label: "Superway",
        colors: ["#324242", "#fffedd", "#ff8826"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "ribbons",
        label: "Ribbons",
        colors: ["#f81735", "#41ead5", "#fdfffc", "#ff9f1c"],
        backgroundColor: "#011627",
      }),
      new Swatch({
        id: "happy-circuits",
        label: "Happy Circuits",
        colors: ["#364f6b", "#3fc1c9", "#fc5185"],
        backgroundColor: "#F5F5F5",
      }),
      new Swatch({
        id: "lemonade",
        label: "Lemonade",
        colors: ["#FFE82D", "#FF21FF"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "night-bus",
        label: "Night Bus",
        colors: ["#1A1A64", "#2C2A89", "#453AA4", "#5C49C6"],
        backgroundColor: "#0B0930",
      }),
      new Swatch({
        id: "vibrano",
        label: "Vibrano",
        colors: ["#302387", "#ff3796", "#00faac", "#fffdaf"],
        backgroundColor: "#111111",
      }),
      new Swatch({
        id: "sepia",
        label: "Sepia",
        colors: ["#bc9369", "#cda882", "#d4b595", "#dcc1a7", "#e3ceb9"],
        backgroundColor: "#eadbcb",
      }),
      new Swatch({
        id: "beachday",
        label: "Beach Day",
        colors: ["#4ecdc4", "#ffe76d", "#ff6b6b", "#f8fff7"],
        backgroundColor: "#1a535c",
      }),
      new Swatch({
        id: "bloodline",
        label: "Bloodline",
        colors: ["#494949", "#7c7a7b", "#FFFFFF", "#ff2d4b"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "highlighters",
        label: "Highlighters",
        colors: ["#ff00f4", "#2aff00", "#fdff00"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "merica",
        label: "Merica",
        colors: ["#ff0020", "#1446ff", "#FFFFFF"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "velvet",
        label: "Velvet",
        colors: ["#560a86", "#f148fb", "#7122fa", "#ffacfc"],
        backgroundColor: "#120129",
      }),
      new Swatch({
        id: "faded-polaroid",
        label: "Faded Polaroid",
        colors: ["#ffb3ba", "#ffdfba", "#ffffba", "#baffc9", "#bae1ff"],
        backgroundColor: "#111111",
      }),
      new Swatch({
        id: "jelly-beans",
        label: "Jelly Beans",
        colors: shuffle([
          "#F44336",
          "#E91E63",
          "#9C27B0",
          "#673AB7",
          "#3F51B5",
          "#3D5AFE",
          "#81D4FA",
          "#1DE9B6",
          "#4CAF50",
          "#8BC34A",
          "#C6FF00",
          "#FFEB3B",
          "#FFA000",
          "#FF3D00",
        ]),
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "rainbow-light",
        label: "Rainbow (light)",
        colors: [
          "#D32F2F",
          "#F57C00",
          "#FBC02D",
          "#388E3C",
          "#1976D2",
          "#7B1FA2",
        ],
        backgroundColor: "#FFFFFF",
      }),
      new Swatch({
        id: "rainbow-dark",
        label: "Rainbow (dark)",
        colors: [
          "#F44336",
          "#FF9800",
          "#FFEB3B",
          "#4CAF50",
          "#2196F3",
          "#9C27B0",
        ],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "trans-flag",
        label: "Trans Flag",
        colors: ["#3498ff", "#ff4889", "#FFFFFF", "#FF4889", "#3498FF"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "pan-flag",
        label: "Pan Flag",
        colors: ["#ff228c", "#ffd800", "#22b1ff"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "intersex-flag",
        label: "Intersex Flag",
        colors: ["#ffd800", "#9e00df"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "bisexual-flag",
        label: "Bisexual Flag",
        colors: ["#d70170", "#0052f5", "#873dcd"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "ace-flag",
        label: "Ace Flag",
        colors: ["#a3a3a3", "#ffffff", "#d900d6"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "agender-flag",
        label: "Agender Flag",
        colors: ["#b9b9b9", "#ffffff", "#8ef434", "#FFFFFF", "#B9B9B9"],
        backgroundColor: "#000000",
      }),
      new Swatch({
        id: "non-binary-flag",
        label: "Non-Binary Flag",
        colors: ["#2d2d2d", "#ffffff", "#a34bea", "#fff420"],
        backgroundColor: "#000000",
      }),
    ];
  }
}
